"""Extract NanoTabICL's `model.py` from the pinned library dump into src/models/.

Why extract instead of committing a copy: the library submodule is the pinned,
authoritative source. Deriving the architecture from it at a known commit keeps
provenance unambiguous and means the file cannot silently drift from the pin.

Run once after cloning (and again if the library pin moves):

    python -m src.utils.vendor_model

Reads `tfm-library/repositories/NanoTabICL.txt` (READ ONLY — nothing is ever
written inside tfm-library/) and writes `src/models/nanotabiclv2.py`.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DUMP = ROOT / "tfm-library" / "repositories" / "NanoTabICL.txt"
OUT = ROOT / "src" / "models" / "nanotabiclv2.py"

MARKER = "FILE: model.py"


def library_pin() -> str:
    try:
        out = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=ROOT / "tfm-library",
            capture_output=True,
            text=True,
            check=True,
        )
        return out.stdout.strip()
    except Exception:
        return "unknown"


def extract(dump_text: str) -> str:
    """Pull the body of model.py out of the flat dump."""
    lines = dump_text.splitlines()

    start = None
    for i, line in enumerate(lines):
        if line.strip() == MARKER:
            start = i + 2  # skip the marker and the '=====' rule beneath it
            break
    if start is None:
        raise SystemExit(f"{DUMP}: could not find a '{MARKER}' section. Has the dump format changed?")

    # The section ends at the next FILE: banner (preceded by a '=====' rule).
    end = len(lines)
    for j in range(start, len(lines)):
        if lines[j].startswith("FILE: ") and j > 0 and set(lines[j - 1].strip()) == {"="}:
            end = j - 1
            break

    body = "\n".join(lines[start:end]).strip("\n")
    if "class NanoTabICLv2" not in body:
        raise SystemExit("Extracted text does not contain NanoTabICLv2; aborting rather than writing garbage.")
    return body


HEADER = '''"""TabICLv2 architecture — vendored verbatim from NanoTabICL.

DO NOT EDIT. This file is generated by `python -m src.utils.vendor_model`, which extracts
`model.py` from the pinned TFM Library dump. Any manual change is lost on the
next extraction, and — worse — would silently make our arms incomparable to the
reference architecture.

    Upstream : https://github.com/soda-inria/nanotabicl  (MIT)
    Paper    : Qu et al. 2026, TabICLv2, arXiv:2602.11139
    Source   : tfm-library/repositories/NanoTabICL.txt
    Pin      : {pin}

Holding this file fixed across every prior arm is the core of the controlled
protocol: architecture, optimizer and budget are constant, and only the
synthetic task distribution varies.

Usage:
    classification: NanoTabICLv2(max_classes=K, out_dim=K)
    regression    : NanoTabICLv2(max_classes=0, out_dim=n_quantiles)

Note the upstream caveat: for regression you must standardise ``y`` yourself and
back-transform the output. In this project that is deliberate — the target
transform is the experimental variable (see src/prior/targets/).
"""

'''


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="verify the vendored file is current; do not write")
    args = ap.parse_args()

    if not DUMP.exists():
        raise SystemExit(
            f"{DUMP} not found.\nRun: git submodule update --init --recursive"
        )

    body = extract(DUMP.read_text(encoding="utf-8", errors="replace"))
    content = HEADER.format(pin=library_pin()) + body + "\n"

    if args.check:
        if not OUT.exists():
            print(f"MISSING: {OUT.relative_to(ROOT)} — run: python -m src.utils.vendor_model")
            return 1
        current = OUT.read_text(encoding="utf-8")
        # Compare bodies only; the header carries the pin and may legitimately differ.
        if current.split('"""', 2)[-1].strip() != body.strip():
            print(f"STALE: {OUT.relative_to(ROOT)} differs from the pinned dump — re-run the vendor script.")
            return 1
        print(f"OK: {OUT.relative_to(ROOT)} matches the pinned dump.")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    (OUT.parent / "__init__.py").touch(exist_ok=True)
    OUT.write_text(content, encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} ({len(body.splitlines())} lines) from pin {library_pin()[:10]}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
